/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SyaratRouteImport } from './routes/syarat'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as PrivasiRouteImport } from './routes/privasi'
import { Route as PesanRouteImport } from './routes/pesan'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as GudangRouteImport } from './routes/gudang'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password.index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as KategoriIndexRouteImport } from './routes/kategori.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AkunIndexRouteImport } from './routes/akun.index'
import { Route as ResetPasswordSuksesRouteImport } from './routes/reset-password.sukses'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as PembayaranSuksesRouteImport } from './routes/pembayaran.sukses'
import { Route as PanduanPengirimanRouteImport } from './routes/panduan.pengiriman'
import { Route as PanduanPengembalianRouteImport } from './routes/panduan.pengembalian'
import { Route as PanduanPembayaranRouteImport } from './routes/panduan.pembayaran'
import { Route as PanduanBelanjaRouteImport } from './routes/panduan.belanja'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as CheckoutVoucherRouteImport } from './routes/checkout.voucher'
import { Route as CheckoutVerifikasiRouteImport } from './routes/checkout.verifikasi'
import { Route as CheckoutPembayaranRouteImport } from './routes/checkout.pembayaran'
import { Route as CheckoutGudangRouteImport } from './routes/checkout.gudang'
import { Route as CheckoutAlamatRouteImport } from './routes/checkout.alamat'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AkunTransaksiIndexRouteImport } from './routes/akun.transaksi.index'
import { Route as BlogTagTagRouteImport } from './routes/blog.tag.$tag'
import { Route as AkunTransaksiIdRouteImport } from './routes/akun.transaksi.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratRoute = SyaratRouteImport.update({
  id: '/syarat',
  path: '/syarat',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivasiRoute = PrivasiRouteImport.update({
  id: '/privasi',
  path: '/privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PesanRoute = PesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangRoute = GudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIndexRoute = KategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkunRoute,
} as any)
const ResetPasswordSuksesRoute = ResetPasswordSuksesRouteImport.update({
  id: '/reset-password/sukses',
  path: '/reset-password/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranSuksesRoute = PembayaranSuksesRouteImport.update({
  id: '/pembayaran/sukses',
  path: '/pembayaran/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanPengirimanRoute = PanduanPengirimanRouteImport.update({
  id: '/panduan/pengiriman',
  path: '/panduan/pengiriman',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanPengembalianRoute = PanduanPengembalianRouteImport.update({
  id: '/panduan/pengembalian',
  path: '/panduan/pengembalian',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanPembayaranRoute = PanduanPembayaranRouteImport.update({
  id: '/panduan/pembayaran',
  path: '/panduan/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanBelanjaRoute = PanduanBelanjaRouteImport.update({
  id: '/panduan/belanja',
  path: '/panduan/belanja',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutVoucherRoute = CheckoutVoucherRouteImport.update({
  id: '/checkout/voucher',
  path: '/checkout/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutVerifikasiRoute = CheckoutVerifikasiRouteImport.update({
  id: '/checkout/verifikasi',
  path: '/checkout/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPembayaranRoute = CheckoutPembayaranRouteImport.update({
  id: '/checkout/pembayaran',
  path: '/checkout/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutGudangRoute = CheckoutGudangRouteImport.update({
  id: '/checkout/gudang',
  path: '/checkout/gudang',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAlamatRoute = CheckoutAlamatRouteImport.update({
  id: '/checkout/alamat',
  path: '/checkout/alamat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunTransaksiIndexRoute = AkunTransaksiIndexRouteImport.update({
  id: '/transaksi/',
  path: '/transaksi/',
  getParentRoute: () => AkunRoute,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/blog/tag/$tag',
  path: '/blog/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunTransaksiIdRoute = AkunTransaksiIdRouteImport.update({
  id: '/transaksi/$id',
  path: '/transaksi/$id',
  getParentRoute: () => AkunRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akun': typeof AkunRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/gudang': typeof GudangRoute
  '/keranjang': typeof KeranjangRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesan': typeof PesanRoute
  '/privasi': typeof PrivasiRoute
  '/promo': typeof PromoRoute
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/alamat': typeof CheckoutAlamatRoute
  '/checkout/gudang': typeof CheckoutGudangRoute
  '/checkout/pembayaran': typeof CheckoutPembayaranRoute
  '/checkout/verifikasi': typeof CheckoutVerifikasiRoute
  '/checkout/voucher': typeof CheckoutVoucherRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/panduan/belanja': typeof PanduanBelanjaRoute
  '/panduan/pembayaran': typeof PanduanPembayaranRoute
  '/panduan/pengembalian': typeof PanduanPengembalianRoute
  '/panduan/pengiriman': typeof PanduanPengirimanRoute
  '/pembayaran/sukses': typeof PembayaranSuksesRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/reset-password/sukses': typeof ResetPasswordSuksesRoute
  '/akun/': typeof AkunIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/produk/': typeof ProdukIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/akun/transaksi/$id': typeof AkunTransaksiIdRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/akun/transaksi/': typeof AkunTransaksiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/gudang': typeof GudangRoute
  '/keranjang': typeof KeranjangRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesan': typeof PesanRoute
  '/privasi': typeof PrivasiRoute
  '/promo': typeof PromoRoute
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/alamat': typeof CheckoutAlamatRoute
  '/checkout/gudang': typeof CheckoutGudangRoute
  '/checkout/pembayaran': typeof CheckoutPembayaranRoute
  '/checkout/verifikasi': typeof CheckoutVerifikasiRoute
  '/checkout/voucher': typeof CheckoutVoucherRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/panduan/belanja': typeof PanduanBelanjaRoute
  '/panduan/pembayaran': typeof PanduanPembayaranRoute
  '/panduan/pengembalian': typeof PanduanPengembalianRoute
  '/panduan/pengiriman': typeof PanduanPengirimanRoute
  '/pembayaran/sukses': typeof PembayaranSuksesRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/reset-password/sukses': typeof ResetPasswordSuksesRoute
  '/akun': typeof AkunIndexRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/kategori': typeof KategoriIndexRoute
  '/produk': typeof ProdukIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/akun/transaksi/$id': typeof AkunTransaksiIdRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/akun/transaksi': typeof AkunTransaksiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akun': typeof AkunRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/gudang': typeof GudangRoute
  '/keranjang': typeof KeranjangRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesan': typeof PesanRoute
  '/privasi': typeof PrivasiRoute
  '/promo': typeof PromoRoute
  '/syarat': typeof SyaratRoute
  '/tentang': typeof TentangRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/alamat': typeof CheckoutAlamatRoute
  '/checkout/gudang': typeof CheckoutGudangRoute
  '/checkout/pembayaran': typeof CheckoutPembayaranRoute
  '/checkout/verifikasi': typeof CheckoutVerifikasiRoute
  '/checkout/voucher': typeof CheckoutVoucherRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/panduan/belanja': typeof PanduanBelanjaRoute
  '/panduan/pembayaran': typeof PanduanPembayaranRoute
  '/panduan/pengembalian': typeof PanduanPengembalianRoute
  '/panduan/pengiriman': typeof PanduanPengirimanRoute
  '/pembayaran/sukses': typeof PembayaranSuksesRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/reset-password/sukses': typeof ResetPasswordSuksesRoute
  '/akun/': typeof AkunIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/produk/': typeof ProdukIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/akun/transaksi/$id': typeof AkunTransaksiIdRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/akun/transaksi/': typeof AkunTransaksiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akun'
    | '/daftar'
    | '/gudang'
    | '/keranjang'
    | '/lupa-password'
    | '/masuk'
    | '/notifikasi'
    | '/pesan'
    | '/privasi'
    | '/promo'
    | '/syarat'
    | '/tentang'
    | '/wishlist'
    | '/blog/$slug'
    | '/checkout/alamat'
    | '/checkout/gudang'
    | '/checkout/pembayaran'
    | '/checkout/verifikasi'
    | '/checkout/voucher'
    | '/kategori/$slug'
    | '/panduan/belanja'
    | '/panduan/pembayaran'
    | '/panduan/pengembalian'
    | '/panduan/pengiriman'
    | '/pembayaran/sukses'
    | '/produk/$slug'
    | '/reset-password/sukses'
    | '/akun/'
    | '/blog/'
    | '/checkout/'
    | '/kategori/'
    | '/produk/'
    | '/reset-password/'
    | '/akun/transaksi/$id'
    | '/blog/tag/$tag'
    | '/akun/transaksi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/gudang'
    | '/keranjang'
    | '/lupa-password'
    | '/masuk'
    | '/notifikasi'
    | '/pesan'
    | '/privasi'
    | '/promo'
    | '/syarat'
    | '/tentang'
    | '/wishlist'
    | '/blog/$slug'
    | '/checkout/alamat'
    | '/checkout/gudang'
    | '/checkout/pembayaran'
    | '/checkout/verifikasi'
    | '/checkout/voucher'
    | '/kategori/$slug'
    | '/panduan/belanja'
    | '/panduan/pembayaran'
    | '/panduan/pengembalian'
    | '/panduan/pengiriman'
    | '/pembayaran/sukses'
    | '/produk/$slug'
    | '/reset-password/sukses'
    | '/akun'
    | '/blog'
    | '/checkout'
    | '/kategori'
    | '/produk'
    | '/reset-password'
    | '/akun/transaksi/$id'
    | '/blog/tag/$tag'
    | '/akun/transaksi'
  id:
    | '__root__'
    | '/'
    | '/akun'
    | '/daftar'
    | '/gudang'
    | '/keranjang'
    | '/lupa-password'
    | '/masuk'
    | '/notifikasi'
    | '/pesan'
    | '/privasi'
    | '/promo'
    | '/syarat'
    | '/tentang'
    | '/wishlist'
    | '/blog/$slug'
    | '/checkout/alamat'
    | '/checkout/gudang'
    | '/checkout/pembayaran'
    | '/checkout/verifikasi'
    | '/checkout/voucher'
    | '/kategori/$slug'
    | '/panduan/belanja'
    | '/panduan/pembayaran'
    | '/panduan/pengembalian'
    | '/panduan/pengiriman'
    | '/pembayaran/sukses'
    | '/produk/$slug'
    | '/reset-password/sukses'
    | '/akun/'
    | '/blog/'
    | '/checkout/'
    | '/kategori/'
    | '/produk/'
    | '/reset-password/'
    | '/akun/transaksi/$id'
    | '/blog/tag/$tag'
    | '/akun/transaksi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkunRoute: typeof AkunRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  GudangRoute: typeof GudangRoute
  KeranjangRoute: typeof KeranjangRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  MasukRoute: typeof MasukRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PesanRoute: typeof PesanRoute
  PrivasiRoute: typeof PrivasiRoute
  PromoRoute: typeof PromoRoute
  SyaratRoute: typeof SyaratRoute
  TentangRoute: typeof TentangRoute
  WishlistRoute: typeof WishlistRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutAlamatRoute: typeof CheckoutAlamatRoute
  CheckoutGudangRoute: typeof CheckoutGudangRoute
  CheckoutPembayaranRoute: typeof CheckoutPembayaranRoute
  CheckoutVerifikasiRoute: typeof CheckoutVerifikasiRoute
  CheckoutVoucherRoute: typeof CheckoutVoucherRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  PanduanBelanjaRoute: typeof PanduanBelanjaRoute
  PanduanPembayaranRoute: typeof PanduanPembayaranRoute
  PanduanPengembalianRoute: typeof PanduanPengembalianRoute
  PanduanPengirimanRoute: typeof PanduanPengirimanRoute
  PembayaranSuksesRoute: typeof PembayaranSuksesRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ResetPasswordSuksesRoute: typeof ResetPasswordSuksesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  KategoriIndexRoute: typeof KategoriIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat': {
      id: '/syarat'
      path: '/syarat'
      fullPath: '/syarat'
      preLoaderRoute: typeof SyaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privasi': {
      id: '/privasi'
      path: '/privasi'
      fullPath: '/privasi'
      preLoaderRoute: typeof PrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesan': {
      id: '/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof PesanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang': {
      id: '/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof GudangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/': {
      id: '/kategori/'
      path: '/kategori'
      fullPath: '/kategori/'
      preLoaderRoute: typeof KategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/': {
      id: '/akun/'
      path: '/'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/reset-password/sukses': {
      id: '/reset-password/sukses'
      path: '/reset-password/sukses'
      fullPath: '/reset-password/sukses'
      preLoaderRoute: typeof ResetPasswordSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran/sukses': {
      id: '/pembayaran/sukses'
      path: '/pembayaran/sukses'
      fullPath: '/pembayaran/sukses'
      preLoaderRoute: typeof PembayaranSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/pengiriman': {
      id: '/panduan/pengiriman'
      path: '/panduan/pengiriman'
      fullPath: '/panduan/pengiriman'
      preLoaderRoute: typeof PanduanPengirimanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/pengembalian': {
      id: '/panduan/pengembalian'
      path: '/panduan/pengembalian'
      fullPath: '/panduan/pengembalian'
      preLoaderRoute: typeof PanduanPengembalianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/pembayaran': {
      id: '/panduan/pembayaran'
      path: '/panduan/pembayaran'
      fullPath: '/panduan/pembayaran'
      preLoaderRoute: typeof PanduanPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan/belanja': {
      id: '/panduan/belanja'
      path: '/panduan/belanja'
      fullPath: '/panduan/belanja'
      preLoaderRoute: typeof PanduanBelanjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/voucher': {
      id: '/checkout/voucher'
      path: '/checkout/voucher'
      fullPath: '/checkout/voucher'
      preLoaderRoute: typeof CheckoutVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/verifikasi': {
      id: '/checkout/verifikasi'
      path: '/checkout/verifikasi'
      fullPath: '/checkout/verifikasi'
      preLoaderRoute: typeof CheckoutVerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pembayaran': {
      id: '/checkout/pembayaran'
      path: '/checkout/pembayaran'
      fullPath: '/checkout/pembayaran'
      preLoaderRoute: typeof CheckoutPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/gudang': {
      id: '/checkout/gudang'
      path: '/checkout/gudang'
      fullPath: '/checkout/gudang'
      preLoaderRoute: typeof CheckoutGudangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/alamat': {
      id: '/checkout/alamat'
      path: '/checkout/alamat'
      fullPath: '/checkout/alamat'
      preLoaderRoute: typeof CheckoutAlamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/transaksi/': {
      id: '/akun/transaksi/'
      path: '/transaksi'
      fullPath: '/akun/transaksi/'
      preLoaderRoute: typeof AkunTransaksiIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/transaksi/$id': {
      id: '/akun/transaksi/$id'
      path: '/transaksi/$id'
      fullPath: '/akun/transaksi/$id'
      preLoaderRoute: typeof AkunTransaksiIdRouteImport
      parentRoute: typeof AkunRoute
    }
  }
}

interface AkunRouteChildren {
  AkunIndexRoute: typeof AkunIndexRoute
  AkunTransaksiIdRoute: typeof AkunTransaksiIdRoute
  AkunTransaksiIndexRoute: typeof AkunTransaksiIndexRoute
}

const AkunRouteChildren: AkunRouteChildren = {
  AkunIndexRoute: AkunIndexRoute,
  AkunTransaksiIdRoute: AkunTransaksiIdRoute,
  AkunTransaksiIndexRoute: AkunTransaksiIndexRoute,
}

const AkunRouteWithChildren = AkunRoute._addFileChildren(AkunRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkunRoute: AkunRouteWithChildren,
  DaftarRoute: DaftarRoute,
  GudangRoute: GudangRoute,
  KeranjangRoute: KeranjangRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  MasukRoute: MasukRoute,
  NotifikasiRoute: NotifikasiRoute,
  PesanRoute: PesanRoute,
  PrivasiRoute: PrivasiRoute,
  PromoRoute: PromoRoute,
  SyaratRoute: SyaratRoute,
  TentangRoute: TentangRoute,
  WishlistRoute: WishlistRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutAlamatRoute: CheckoutAlamatRoute,
  CheckoutGudangRoute: CheckoutGudangRoute,
  CheckoutPembayaranRoute: CheckoutPembayaranRoute,
  CheckoutVerifikasiRoute: CheckoutVerifikasiRoute,
  CheckoutVoucherRoute: CheckoutVoucherRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  PanduanBelanjaRoute: PanduanBelanjaRoute,
  PanduanPembayaranRoute: PanduanPembayaranRoute,
  PanduanPengembalianRoute: PanduanPengembalianRoute,
  PanduanPengirimanRoute: PanduanPengirimanRoute,
  PembayaranSuksesRoute: PembayaranSuksesRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ResetPasswordSuksesRoute: ResetPasswordSuksesRoute,
  BlogIndexRoute: BlogIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  KategoriIndexRoute: KategoriIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  BlogTagTagRoute: BlogTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
